#cloud-config
package_upgrade: true
packages:
  - nginx
write_files:
  - content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Azure Explorer app</title>
      </head>
      <body>
        <h2>Azure Explorer app</h2>
        <ul>
          <li><b>Backend VM:</b> ${HOSTNAME}</li>
          <li><b>Current time:</b> ${DATE}</li>
        </ul>
      </body>
    path: /tmp/index.template.html
runcmd:
  - DATE=$(date +"%Y-%m-%dT%H:%M:%S%z") HOSTNAME=$(hostname -f) envsubst '$DATE,$HOSTNAME' < /tmp/index.template.html > /var/www/html/index.nginx-debian.html
  - chown www-data:www-data /var/www/html/index.nginx-debian.html
  - chmod 0644 /var/www/html/index.nginx-debian.html
  - systemctl enable --now nginx.service
